Tracking機能とtracking viewの実装
ByeongGwan-Seo/PriceTracker_dev pull request #40
Opened 2024-12-06 08:09 UTC by ByeongGwan-Seo

## 📝 概要

- **目的**: DetailViewでのTracking機能実装とTrackingしたタイトルの確認ができるTrackingViewの実装

---

## 🔄 変更内容

- [x] [変更点1: 機能やコードの追加・修正内容]
- TrackingViewModelのloadTrackingInfos()をcombineで実装してみました。こちらの形で合ってるかの確認をいただきたいです。
- [x] [変更点3: UIや設定の変更があれば記載]
- DetailView内のBasicInfoViewにTrackingボタンを追加しました。

---

## ✅ 確認事項

- [ ] コードレビュー済み
- [ ] テストケースを追加/更新済み
- [ ] 動作確認済み（環境: [ブラウザ/デバイスなど]）
- [ ] 関連ドキュメント更新済み（必要であれば）

---

## 📌 その他の補足情報

- @AppStorageでUserDefaultsにTracking情報をセーブする様にしました。
- 素直に申しますと既存のViewModelのロジックをcombine的に改修するのは現在難しいと思われるため、新しく作成する画面のロジックから適用して行こうとしています。
- 現在状態は、単純にTrackingしているタイトルの表示するだけですが、Trackingしているタイトルの詳細情報表示、ローカルPush通知などを作っていきたいと思っています。

2024-12-06 08:12 UTC, ByeongGwan-Seo commented
@pakusongi 
今回PRでレビューお願いしたいところはTrackingViewModelのところです。
私なりにTrackingViewModelでUserDefaultsからデータをロードするところをcombine的に作ってみました。   
この様な形で大丈夫そうでしたら、勉強した内容を一個づつ適用して行きたいです。

2024-12-07 12:21 UTC, pakusongi requested changes
@ByeongGwan-Seo 
実装お疲れ様です。
ちょっと細かい内容が多いですが確認お願いします。

レビューの内容にないですが
ビルドすると今回レビュー対象でswiftlintからのwarringが結構あるのでその対応もお願いします。

これは好みのもんだいですが改行が多くて
ちょっと読みにくかったりするので
1行だけだったりする場合は改行なしでお願いします。

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/TrackingViewController.swift
> +        hostingController.didMove(toParent: self)
landscape時にレイアウトの崩れが発生するので対応お願いします。

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +                    let localizedMessage = String(
可読性が低いので別のメソッドにして簡潔にしましょう
参考までに

@MainActor
private func updateErrorState(error: Error) {
    status = .error
    let localizedMessage = String(
        format: NSLocalizedString("detail_error_message",
                                  comment: "error occurred while loading detail"), "\(error)")
    errorMessage = ErrorMessage(message: localizedMessage)
}

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +        if let price = Double(inputPrice), price > 0 {
`inputPrice` に関するベリデーションチェックは専用メソッドを作成しましょう

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +        if let price = Double(inputPrice), price > 0 {
if 文の中が深く可動性もよくないので
基本的に guardを使って条件が偽りの場合は 早期リターンするようにお願いします。
ifだとコードの深いネストになるケースが多いので防ぎたいです

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +        if let trackingInfos = loadTrackingInfos() {
デバッグコードは #if DEBUG を活用しましょう

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +    func saveTrackingInfos(_ trackingInfos: [TrackingInfo]) {
できれば 
データ永続化理ゾックは分離して、viewmodelの責務は軽減したほうがいいです

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +    func loadTrackingInfos() -> [TrackingInfo]? {
ここも
できれば
データ永続化理ゾックは分離して、viewmodelの責務は軽減したほうがいいです

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +    @AppStorage("trackingInfos") private var savedTrackingInfosData: Data = Data()
AppStorage使う発想いいと思います。
SwiftUIらしい

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +            .replaceError(with: [])
.replaceError(with: []) はエラーを隠すので、実際に何が起きたかがわからなくなります。
デコードエラーのログを残し、エラーの原因をデバッグできるように改善お願いします。

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +        if let encodedData = try? JSONEncoder().encode(trackingInfos) {
保存に失敗した際にログを出力して原因を把握できるようにしましょう

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +        "User Price: $\(item.userPrice ?? "")"
ローカライズを活用してください

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +        if let encodedData = try? JSONEncoder().encode(trackingInfos) {
userDefaultsからのget, saveを repository パターンを活用するのもchatgptとかで検索してみてください

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/BasicInfoView.swift
> +                        .resizable()
AsyncImage に指定している frame(width: 150, height: 100) は画像が正確にそのサイズで表示されますが、画像のアスペクト比を崩す可能性がますので
aspect比を持たせた方がいいかもですね

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/BasicInfoView.swift
> +                Text("Retail Price: $\(item.deals.first?.retailPrice ?? "")")
ローカライズの活用をお願いします

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +                Text("Enter Price")
ローカライズを利用お願いします。

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +            Color.black.opacity(showTrackingAlert ? 0.4 : 0)
ZStack の Color.black.opacity による背景処理は機能していますが、background 修飾子を使うとコードが簡潔になりそうですがどうですか？

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +        ZStack {
この　zstack　は必要ですか？

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                    title: Text("error_alert_title"),
今更ですが
可読性がが低いので
LocalizedStringKeyを活用お願いします

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                switch detailViewModel.status {
switch 文の中で case ごとに直接ビューを構築していますが、ビュー構築ロジックをサブビューやメソッドに分割した方が可読性はいいと思います

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                        detailViewModel.onPriceInputCancelled()
onCancel: detailViewModel.onPriceInputCancelled
のような書き方もできます

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                DetailTrackingOverlayView(
DetailTrackingOverlayViewって常にViewの作成されていて
showTrackingAlertの値によってalphaが変わるだけにみえるのでパフォーマンスに良くない気がしますね
showTrackingAlert が true時ののみDetailTrackingOverlayViewを表示するような実装の方が良さそうですね

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +                        if let index = trackingViewModel.trackingInfos.firstIndex(
削除のロジックが List 内で直接記述されていますが、ViewModel に責務を委譲すると、コードの可読性と再利用性が向上します。

2024-12-07 12:21 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +            List(trackingViewModel.trackingInfos, id: \.uuidString) { trackingInfo in
List の各アイテムが UUID で識別されていますが、頻繁に変更される場合、SwiftUI の識別処理が非効率になることがあるので、
Identifiable プロトコルを TrackingInfo に適用することで、より簡潔に管理できます。

var id: String { uuidString }

2024-12-12 03:46 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +        ZStack {
@ByeongGwan-Seo 
返答遅くなりましてすみません。
確かに、.overlayを使おうとしていますので、ZStackは必要ではないと思います。
.overlayを使う方法で修正します。

2024-12-12 08:58 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +            Color.black.opacity(showTrackingAlert ? 0.4 : 0)
@pakusongi 
当内容はZStack自体にbackgroundをつけたり、これが表示されるDetailViewのBackgroundを調整したりしましたが、Layoutで表示される画面周りたけ、背景効果が適用される問題がありましたため、このままでおきたいと思います。

2024-12-13 01:56 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/TrackingViewController.swift
> +        hostingController.didMove(toParent: self)
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/6ed19ee6eb2b97f2821feaa8829b8c0e528712c4
上記コミットで対応しました。

2024-12-13 01:58 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +                    let localizedMessage = String(
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/c7d5cc33acd20bccf14e3a71d3852d32a3776966
上記コミットで対応しました。

2024-12-13 01:59 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +        if let price = Double(inputPrice), price > 0 {
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/c74c77d87cd93db4044fae85d4f156fb40c53722
上記コミットで対応しました。

2024-12-13 02:00 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +        if let trackingInfos = loadTrackingInfos() {
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/0c0428cd122c0bad655ec05739b67b4b34a257e3
上記コミットで対応しました。

2024-12-13 02:02 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +    func saveTrackingInfos(_ trackingInfos: [TrackingInfo]) {
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/20cf7c8fff34500f44a9b69af745e2a7d18f6b46
上記コミットで対応しました。

2024-12-13 02:03 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/DetailViewModel.swift
> +    func loadTrackingInfos() -> [TrackingInfo]? {
@pakusongi 
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/20cf7c8fff34500f44a9b69af745e2a7d18f6b46
上記コミットで対応しました。

2024-12-13 02:05 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +            .replaceError(with: [])
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/280e0c17046edc756d736bb334b4428974334df5
上記コミットで対応しました。

2024-12-13 02:06 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +        if let encodedData = try? JSONEncoder().encode(trackingInfos) {
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/d7378b1b3c70a429f1fab535371fecd148f8955c
上記コミットで対応しました。

2024-12-13 02:07 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewModels/TrackingViewModel.swift
> +        "User Price: $\(item.userPrice ?? "")"
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/3a309dca43de80d7b9cb4660ace2008bb55ad2bd
上記コミットで対応しました。

2024-12-13 02:08 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/BasicInfoView.swift
> +                        .resizable()
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/0db1e954790e48a56853a0a52ff756ac45fb5e37
上記コミットで対応しました。

2024-12-13 02:08 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/BasicInfoView.swift
> +                Text("Retail Price: $\(item.deals.first?.retailPrice ?? "")")
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/3a309dca43de80d7b9cb4660ace2008bb55ad2bd
上記コミットで対応しました。

2024-12-13 02:08 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +                Text("Enter Price")
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/3a309dca43de80d7b9cb4660ace2008bb55ad2bd
上記コミットで対応しました。

2024-12-13 02:11 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +        ZStack {
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/08815c03b35210432f03afcc1697b9daa87342d9
上記コミットで対応しました。

2024-12-13 02:11 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                    title: Text("error_alert_title"),
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/3a309dca43de80d7b9cb4660ace2008bb55ad2bd
上記コミットで対応しました。

2024-12-13 02:17 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                switch detailViewModel.status {
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/6c7419c0eb46bbe8204b4c71b1b8aa8661f305fb
上記コミットで対応しました。
現在extensionして作りましたが、今後ファイル分けします。

2024-12-13 02:17 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                        detailViewModel.onPriceInputCancelled()
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/7ccbe368c9c4ec858dc56a6e4ba2e8771f624628
上記コミットで対応しました。

2024-12-13 02:18 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailView.swift
> +                DetailTrackingOverlayView(
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/7ccbe368c9c4ec858dc56a6e4ba2e8771f624628
上記コミットで対応しました。

2024-12-13 02:18 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +                        if let index = trackingViewModel.trackingInfos.firstIndex(
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/1b983daae0e549589535fcb8185d6713359b5dd2
上記コミットで対応しました。

2024-12-13 02:19 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +            List(trackingViewModel.trackingInfos, id: \.uuidString) { trackingInfo in
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/f0fb5ec8188a0aa96c3e987174021645fe26ff0a
上記コミットで対応しました。

2024-12-13 02:20 UTC, ByeongGwan-Seo commented
@pakusongi 
re-requestお送りしました。確認お願いします。

2024-12-15 23:42 UTC, pakusongi commented
実装お疲れ様です
もう一度コードの見直しをお願いします。

2024-12-15 23:47 UTC, pakusongi commented
ローカライズですが全てのローカライズキーを
正しく定義するか
言語一つにしてください。

2024-12-15 23:49 UTC, pakusongi requested changes
@ByeongGwan-Seo
実装お疲れ様です
もう一度コードの見直しをお願いします。

ローカライズですが全てのローカライズキーを
正しく定義するか
言語一つにしてください。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Search/SearchView.swift
> +            title: Text("Error"),
Localizable.string に　"error_alert_title"　があったのでそれを使ってください

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/Model/TrackingModel.swift
> +    var id: UUID
mutabilityに変数にした理由はなんですか？

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/Service/TrackingInfoService.swift
> +    func loadTrackingInfos() -> [TrackingInfo]?
nits
nilもわるくないですが
`func loadTrackingInfos() -> Result<[TrackingInfo], Error>`
でエラーの状態を明確にするのもいいと思います。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            NSLayoutConstraint.activate([
NSLayoutConstraint.activate　のように
レイアウトの設定は別のメソッドに分けた方がコードが読みやすくなります。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +    private var hostingController: UIHostingController<SearchView>?
viewDidLoadで初期化するのでnilになる可能性はないと思います。
non-optionalに変更するか lazy varに遅延プロパティにすると
無駄なnull checkはなくなると思います。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
hostingControllerのviewにautolayoutの制約が正しく動作する場合はこのメソッドは不要です。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            self.hostingController?.view.layoutIfNeeded()
layoutIfNeeded, setNeedsLayoutは基本自動で処理されるので省略可能です。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            self.hostingController?.view.frame = self.view.bounds
view.frameを明示的に指定しなくても正しく動作する場合はこのコードはいらないです

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/ViewController/TrackingViewController.swift
> +        hostingController.didMove(toParent: self)
UIHostingController関連は SearchViewControllerのフィードバックから確認お願いします。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +            Text("Tracking Information:")
ローカルライズを使いましょう

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +                    Text("\(trackingInfo.title)")
Text("\(trackingInfo.title)") って
Text(trackingInfo.title)まま使えます。

2024-12-15 23:49 UTC, pakusongi commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +    @Binding var showTrackingAlert: Bool
showTrackingAlert って必要ですか？

2024-12-16 06:19 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Model/TrackingModel.swift
> +    var id: UUID
@pakusongi 
すみません。固有IDとなる部分を変数にしたのは私の間違いです。

2024-12-16 10:10 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
@pakusongi 
ありがとうございます。コメントアウトして確認した結果、当メソッドがなくてもUIの崩れはないでしたので、削除します。

2024-12-16 11:23 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +    @Binding var showTrackingAlert: Bool
@pakusongi 
overlayを表示するロジックを片付ける中で見逃した様です。注意します。

2024-12-16 11:24 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Detail/DetailTrackingOverlayView.swift
> +    @Binding var showTrackingAlert: Bool
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/98decb99efa41a8c12c563efc09fb097799a69e3
上記コミットで対応しました。

2024-12-16 11:25 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +                    Text("\(trackingInfo.title)")
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/3de92bf97cc198d3db100e04bdf997317fc3a372
上記コミットで対応しました。尚、LocalizationをEN一個に片づけしました。

2024-12-16 11:25 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Views/Tracking/TrackingView.swift
> +            Text("Tracking Information:")
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/3de92bf97cc198d3db100e04bdf997317fc3a372
上記コミットで対応しました。

2024-12-16 11:26 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            self.hostingController?.view.frame = self.view.bounds
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/a212901e1595b5863d5893b7b0c0d4940f696ae1
上記コミットでVC両方対応しました。

2024-12-16 11:28 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            self.hostingController?.view.layoutIfNeeded()
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/a212901e1595b5863d5893b7b0c0d4940f696ae1
上記コミットでVC両方対応しました。

2024-12-16 11:28 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/a212901e1595b5863d5893b7b0c0d4940f696ae1
上記コミットでVC両方対応しました。

2024-12-16 11:28 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            NSLayoutConstraint.activate([
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/a69f0440b94b7951844aeec6c7f2222447abe960
上記コミットで対応しました。

2024-12-16 11:29 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +    private var hostingController: UIHostingController<SearchView>?
@pakusongi
https://github.com/ByeongGwan-Seo/PriceTracker_dev/commit/a69f0440b94b7951844aeec6c7f2222447abe960
上記コミットで対応しました。

2024-12-16 11:30 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/ViewController/SearchViewController.swift
> +            NSLayoutConstraint.activate([
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/e647b797dcebe4eb6fde6f992100cac9b07ec8c3
上記コミットで対応しました。

2024-12-16 11:42 UTC, ByeongGwan-Seo commented on PriceTracker/PriceTracker/Service/TrackingInfoService.swift
> +    func loadTrackingInfos() -> [TrackingInfo]?
@pakusongi 
https://github.com/ByeongGwan-Seo/PriceTracker_dev/pull/40/commits/bb967064c13e15c270dfb055ff9d48b85fb06977
上記コミットで対応しました。

2024-12-16 11:44 UTC, ByeongGwan-Seo commented
@pakusongi 
re-requestお送りしました。
lint warningの場合、修正箇所が多いため、別ブランチで一気に直してマージします。

2024-12-17 03:05 UTC, pakusongi approved these changes
@ByeongGwan-Seo 
LGTM お疲れ様でした。

2024-12-19 01:01 UTC, merged